// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.TanAn.Infrastructure.Persistence;

#nullable disable

namespace Service.TanAn.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TanAnDbContext))]
    [Migration("20260926013505_VillageAdministrationScope")]
    partial class VillageAdministrationScope
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Service.TanAn.Domain.Entities.ApThon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("NguoiSuaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NguoiTaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("XaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.HasIndex("XaId");

                    b.ToTable("ApThons");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.BienDongDanCu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanBoGhiNhan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CanBoId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileDinhKemUrl")
                        .HasColumnType("text");

                    b.Property<int>("LoaiBienDong")
                        .HasColumnType("integer");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayPhatSinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("NhanKhauId")
                        .HasColumnType("uuid");

                    b.Property<string>("NoiDen")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NoiDenOrDi")
                        .HasColumnType("text");

                    b.Property<string>("NoiDi")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CanBoId");

                    b.HasIndex("NhanKhauId", "NgayPhatSinh");

                    b.ToTable("BienDongDanCus");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.DoiTuongAnSinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int>("LoaiDoiTuong")
                        .HasColumnType("integer");

                    b.Property<decimal>("MucTroCapHangThang")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("NgayBatDauHuong")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayKetThucHuong")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("NhanKhauId")
                        .HasColumnType("uuid");

                    b.Property<string>("SoQuyetDinh")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NhanKhauId", "LoaiDoiTuong");

                    b.ToTable("DoiTuongAnSinhs", null, t =>
                        {
                            t.HasCheckConstraint("CK_AnSinh_MucTroCap", "\"MucTroCapHangThang\" >= 0");

                            t.HasCheckConstraint("CK_AnSinh_ThoiGian", "\"NgayKetThucHuong\" IS NULL OR \"NgayKetThucHuong\" >= \"NgayBatDauHuong\"");
                        });
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.Groups", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.HoGiaDinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApThon")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("ApThonId")
                        .HasColumnType("uuid");

                    b.Property<string>("CCCDChuHo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("MaSoHo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TenChuHo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApThonId");

                    b.HasIndex("MaSoHo")
                        .IsUnique();

                    b.ToTable("HoGiaDinhs");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.LichSuTroCap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoiTuongAnSinhId")
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayChiTra")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NguoiChiTra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("NguoiChiTraId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ThangNam")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiChiTraId");

                    b.HasIndex("DoiTuongAnSinhId", "ThangNam");

                    b.ToTable("LichSuTroCaps", null, t =>
                        {
                            t.HasCheckConstraint("CK_TroCap_SoTien", "\"SoTien\" > 0");
                        });
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.LichSuXuLyHoSo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("NguoiSuaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NguoiTaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NguoiXuLyId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TrangThaiCu")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThaiMoi")
                        .HasColumnType("integer");

                    b.Property<Guid>("YeuCauId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NguoiXuLyId");

                    b.HasIndex("YeuCauId", "NgayTao");

                    b.ToTable("LichSuXuLyHoSos");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.LogThaoTacNguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("AfterChange")
                        .HasColumnType("text");

                    b.Property<string>("BeforeChange")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IPAddress")
                        .HasColumnType("text");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LogThaoTacNguoiDungs");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Expands")
                        .HasColumnType("boolean");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("LienKet")
                        .HasColumnType("text");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ModuleChaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PhanHeId")
                        .HasColumnType("uuid");

                    b.Property<int>("PhanLoai")
                        .HasColumnType("integer");

                    b.Property<string>("TenModule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ViTri")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuleChaId");

                    b.HasIndex("PhanHeId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.NhanKhau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("DanToc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("integer");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MaHoGiaDinh")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NgheNghiep")
                        .HasColumnType("text");

                    b.Property<string>("QuanHeVoiChuHo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TamTru")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ThuongTru")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TonGiao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.Property<string>("TrinhDoHocVan")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CCCD")
                        .IsUnique()
                        .HasFilter("\"CCCD\" IS NOT NULL AND \"CCCD\" <> ''");

                    b.HasIndex("MaHoGiaDinh", "TrangThai");

                    b.ToTable("NhanKhaus");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSync")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionCode")
                        .HasColumnType("integer");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PermissionParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionParentId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.PhanHe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HoatDong")
                        .HasColumnType("boolean");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("PhanHes");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.PhanLoaiHo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DenNgay")
                        .HasColumnType("date");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<Guid>("HoGiaDinhId")
                        .HasColumnType("uuid");

                    b.Property<int>("LoaiHo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("NguoiSuaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NguoiTaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("SoQuyetDinh")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("TuNgay")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("HoGiaDinhId")
                        .IsUnique()
                        .HasFilter("\"DenNgay\" IS NULL");

                    b.ToTable("PhanLoaiHos", null, t =>
                        {
                            t.HasCheckConstraint("CK_PhanLoaiHo_ThoiGian", "\"DenNgay\" IS NULL OR \"DenNgay\" >= \"TuNgay\"");
                        });
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.PhuTrachThon", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApThonId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "ApThonId");

                    b.HasIndex("ApThonId");

                    b.ToTable("PhuTrachThons");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsSync")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Mota")
                        .HasColumnType("text");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.RoleModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RoleModules");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.SystemParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSync")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SystemParameters");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.TepDinhKem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("DungLuong")
                        .HasColumnType("bigint");

                    b.Property<string>("DuongDanLuu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LoaiTep")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("NguoiSuaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NguoiTaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenTep")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("YeuCauId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("YeuCauId");

                    b.ToTable("TepDinhKems", null, t =>
                        {
                            t.HasCheckConstraint("CK_TepDinhKem_DungLuong", "\"DungLuong\" >= 0");
                        });
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.ThanhVienHo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DenNgay")
                        .HasColumnType("date");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<Guid>("HoGiaDinhId")
                        .HasColumnType("uuid");

                    b.Property<bool>("LaChuHo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("NguoiSuaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NguoiTaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NhanKhauId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuanHeVoiChuHo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("TuNgay")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("HoGiaDinhId")
                        .IsUnique()
                        .HasFilter("\"DenNgay\" IS NULL AND \"LaChuHo\" = TRUE");

                    b.HasIndex("NhanKhauId")
                        .IsUnique()
                        .HasFilter("\"DenNgay\" IS NULL");

                    b.HasIndex("HoGiaDinhId", "TuNgay");

                    b.ToTable("ThanhVienHos", null, t =>
                        {
                            t.HasCheckConstraint("CK_ThanhVienHo_ThoiGian", "\"DenNgay\" IS NULL OR \"DenNgay\" >= \"TuNgay\"");
                        });
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.ThongBaoThon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApThonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DaDocLuc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("NguoiNhanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NguoiSuaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NguoiTaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApThonId");

                    b.HasIndex("NguoiNhanId", "NgayTao");

                    b.ToTable("ThongBaoThons");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApThon")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyPublic")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastLoginIp")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhanLoai")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("TotalLogin")
                        .HasColumnType("integer");

                    b.Property<int>("TotalLoginFaild")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.UserGroups", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PhongBanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PhongBanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("PhongBanId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.UserRoleHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChuyenTrangId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChuyenTrangName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.PrimitiveCollection<List<string>>("ListRoleAfterEdit")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("ListRoleBeforeEdit")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("LstChuyenMucAfterEdit")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("LstChuyenMucBeforeEdit")
                        .HasColumnType("text[]");

                    b.Property<string>("TenNguoiThucHien")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UserRoleHistories");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.Xa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("NguoiSuaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NguoiTaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("Xas");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.YeuCauNguoiDan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApThonId")
                        .HasColumnType("uuid");

                    b.Property<string>("CCCDNguoiYeuCau")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("CanBoXuLy")
                        .HasColumnType("text");

                    b.Property<Guid?>("CanBoXuLyId")
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChuCanBo")
                        .HasColumnType("text");

                    b.Property<string>("HoTenNguoiYeuCau")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LoaiYeuCau")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("MaYeuCau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("NguoiNopId")
                        .HasColumnType("uuid");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApThonId");

                    b.HasIndex("CanBoXuLyId");

                    b.HasIndex("MaYeuCau")
                        .IsUnique();

                    b.HasIndex("NguoiNopId");

                    b.HasIndex("TrangThai", "NgayGui");

                    b.ToTable("YeuCauNguoiDans");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.ApThon", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.Groups", "DonVi")
                        .WithOne()
                        .HasForeignKey("Service.TanAn.Domain.Entities.ApThon", "GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Service.TanAn.Domain.Entities.Xa", "Xa")
                        .WithMany("Thons")
                        .HasForeignKey("XaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonVi");

                    b.Navigation("Xa");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.BienDongDanCu", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.User", "CanBo")
                        .WithMany()
                        .HasForeignKey("CanBoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Service.TanAn.Domain.Entities.NhanKhau", "NhanKhau")
                        .WithMany("BienDongs")
                        .HasForeignKey("NhanKhauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanBo");

                    b.Navigation("NhanKhau");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.DoiTuongAnSinh", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.NhanKhau", "NhanKhau")
                        .WithMany("ChinhSachAnSinh")
                        .HasForeignKey("NhanKhauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanKhau");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.HoGiaDinh", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.ApThon", "DiaBan")
                        .WithMany("HoGiaDinhs")
                        .HasForeignKey("ApThonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DiaBan");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.LichSuTroCap", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.DoiTuongAnSinh", "DoiTuongAnSinh")
                        .WithMany("LichSuTroCaps")
                        .HasForeignKey("DoiTuongAnSinhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.TanAn.Domain.Entities.User", "CanBoChiTra")
                        .WithMany()
                        .HasForeignKey("NguoiChiTraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CanBoChiTra");

                    b.Navigation("DoiTuongAnSinh");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.LichSuXuLyHoSo", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.User", "NguoiXuLy")
                        .WithMany()
                        .HasForeignKey("NguoiXuLyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Service.TanAn.Domain.Entities.YeuCauNguoiDan", "YeuCau")
                        .WithMany("LichSuXuLy")
                        .HasForeignKey("YeuCauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiXuLy");

                    b.Navigation("YeuCau");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.Module", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.Module", "ModuleCha")
                        .WithMany()
                        .HasForeignKey("ModuleChaId");

                    b.HasOne("Service.TanAn.Domain.Entities.PhanHe", "PhanHe")
                        .WithMany()
                        .HasForeignKey("PhanHeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ModuleCha");

                    b.Navigation("PhanHe");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.NhanKhau", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.HoGiaDinh", "HoGiaDinh")
                        .WithMany("ThanhVien")
                        .HasForeignKey("MaHoGiaDinh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoGiaDinh");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.Permission", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.Permission", "PermissionParent")
                        .WithMany()
                        .HasForeignKey("PermissionParentId");

                    b.Navigation("PermissionParent");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.PhanLoaiHo", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.HoGiaDinh", "HoGiaDinh")
                        .WithMany("LichSuPhanLoai")
                        .HasForeignKey("HoGiaDinhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoGiaDinh");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.PhuTrachThon", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.ApThon", "Thon")
                        .WithMany()
                        .HasForeignKey("ApThonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.TanAn.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Thon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.TepDinhKem", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.YeuCauNguoiDan", "YeuCau")
                        .WithMany("TepDinhKems")
                        .HasForeignKey("YeuCauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("YeuCau");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.ThanhVienHo", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.HoGiaDinh", "HoGiaDinh")
                        .WithMany("LichSuThanhVien")
                        .HasForeignKey("HoGiaDinhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.TanAn.Domain.Entities.NhanKhau", "NhanKhau")
                        .WithMany("LichSuHoGiaDinh")
                        .HasForeignKey("NhanKhauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoGiaDinh");

                    b.Navigation("NhanKhau");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.ThongBaoThon", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.ApThon", "Thon")
                        .WithMany()
                        .HasForeignKey("ApThonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.TanAn.Domain.Entities.User", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("NguoiNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiNhan");

                    b.Navigation("Thon");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.UserPermission", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.TanAn.Domain.Entities.Groups", "PhongBan")
                        .WithMany()
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.TanAn.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("PhongBan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.TanAn.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.YeuCauNguoiDan", b =>
                {
                    b.HasOne("Service.TanAn.Domain.Entities.ApThon", "Thon")
                        .WithMany()
                        .HasForeignKey("ApThonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Service.TanAn.Domain.Entities.User", "NguoiXuLy")
                        .WithMany()
                        .HasForeignKey("CanBoXuLyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Service.TanAn.Domain.Entities.User", "NguoiNop")
                        .WithMany()
                        .HasForeignKey("NguoiNopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiNop");

                    b.Navigation("NguoiXuLy");

                    b.Navigation("Thon");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.ApThon", b =>
                {
                    b.Navigation("HoGiaDinhs");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.DoiTuongAnSinh", b =>
                {
                    b.Navigation("LichSuTroCaps");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.HoGiaDinh", b =>
                {
                    b.Navigation("LichSuPhanLoai");

                    b.Navigation("LichSuThanhVien");

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.NhanKhau", b =>
                {
                    b.Navigation("BienDongs");

                    b.Navigation("ChinhSachAnSinh");

                    b.Navigation("LichSuHoGiaDinh");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.Xa", b =>
                {
                    b.Navigation("Thons");
                });

            modelBuilder.Entity("Service.TanAn.Domain.Entities.YeuCauNguoiDan", b =>
                {
                    b.Navigation("LichSuXuLy");

                    b.Navigation("TepDinhKems");
                });
#pragma warning restore 612, 618
        }
    }
}
